### ISSUE TITLE
Plugin does not show Locust section on build overview page

### ISSUE THREAD

**Issue by wizardshill** [orn0t/teamcity-locustio#1]
TeamCity Enterprise 2019.2.2 (build 71923)

**Comment by wizardshill** [comment]
The agent module is trying to parse the wrong csv file (build_%s_requests.csv).
The latest v0.14.5 of locustio is generating:

- build_#_failures.csv
- build_#_stats.cs
- build_#_stats_history.csv

maybe look for "build_%s_requests.csv" and if that doesn't exist try loading "build_%s_stats.csv"

**Comment by orn0t** [comment]
Was developed by using 2018.2.2,
there was major changes in 2019 interface so i need to check this out.

**Comment by orn0t** [comment]
Hi @wizardshill, sorry for long response, 
please check new **1.1** version

I just updated plugin for latest Locust.io and latest TeamCity (modern UI support included)
