### ISSUE TITLE
Plugin does not fail the build when errors occur

### ISSUE THREAD

**Issue by wizardshill** [orn0t/teamcity-locustio#2]
TeamCity Enterprise 2019.2.2 (build 71923)

Maximum failed requests: 1

[11:16:44]

[Step 2/2] Error report
[11:16:44]

[Step 2/2]  # occurrences      Error                                                                                               
[11:16:44]

[Step 2/2] --------------------------------------------------------------------------------------------------------------------------------------------
[11:16:44]

[Step 2/2]  1                  AUTH ***@***: "'No Cookies'"                      
[11:16:44]

[Step 2/2]  1                  AUTH ***@***: "'No Cookies'"                      
[11:16:44]

[Step 2/2]  1                  AUTH ***@***: "'No Cookies'"                      
[11:16:44]

[Step 2/2]  1                  AUTH ***@***: "'No Cookies'"                      
[11:16:44]

[Step 2/2]  1                  AUTH ***@***: "'No Cookies'"                      
[11:16:44]

[Step 2/2] --------------------------------------------------------------------------------------------------------------------------------------------
[11:16:44]

[Step 2/2]

**Comment by wizardshill** [comment]
The agent module is trying to parse the wrong csv file (build_%s_requests.csv).
The latest v0.14.5 of locustio is generating:

- build_#_failures.csv
- build_#_stats.cs
- build_#_stats_history.csv

maybe look for "build_%s_requests.csv" and if that doesn't exist try loading "build_%s_stats.csv"

**Comment by orn0t** [comment]
Responded in #1 , closing this issue
